// <-- Ludic numbers -->

/*
  The ludic numbers are a set of numbers related to prime numbers, as they are generated by sieving. Below is the method to generate such numbers.

  Generation of ludic numbers:
  First take the natural numbers starting from 2.
  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 ...]
  1 is the first ludic number -> Ludic = {1}.
  Note that you should not remove every 1th-indexed number, despite 1 being ludic.

  Take the first element from the resulting array: 2.
  Remove every 2nd indexed number.
  [3, 5, 7, 9, 11, 13, 15, 17, 19 ...]
  The first deleted number is 2 -> Ludic = {1, 2}.

  Take the first element from the resulting array: 3.
  Remove every 3rd indexed number.
  [5, 7, 11, 13, 17, 19 ...]
  The first deleted number is 3 -> Ludic = {1, 2, 3}.

  Take the first element from the resulting array: 5.
  Remove every 5th number.
  [7, 11, 13, 19 ...]
  The first deleted number is 5 -> Ludic = {1, 2, 3, 5}.

  etc...
  Write a function to return an integer: the sum of the first n ludic numbers.
  You can assume that 1 ≤ n ≤ 10000.

  Sample Tests:
  sumLudic(1) -> 1
  sumLudic(10) -> 107
  sumLudic(25) -> 1100
*/

// <-- Solution -->
const sumLudic = (function () {
  let memo = [1];
  const plus = (v, w) => v + w;
  let a = Array.from({ length: 130000 }, (_, i) => i + 2);

  while (a.length) {
    memo.push(a[0]);
    a = a.filter((_, i) => i % a[0]);
  }

  memo = (function scanl(fn, z, a) {
    let r = [z, ...a];

    for (let i = 1; i in r; i++) {
      r[i] = z = fn(z, r[i]);
    }

    return r;
  })(plus, 0, memo);

  return (n) => memo[n];
})();
